### ISSUE TITLE
CLI Roadmap for V1

### ISSUE THREAD

**Issue by AffectedArc07** [DMPM-Team/cli#1]
Commands:
- [x] `dmpm init` - Sets up a repository for use with DMPM
- [ ] `dmpm add <dependency>` - Adds a dependency to the existing project
- [ ] `dmpm remove <dependency>` - Removes a dependency from the existing project
- [ ] `dmpm update [dependency]` - Updates one (or all) of the dependencies
- [ ] `dmpm check [dependency]` - Checks one (or all) dependencies for updates, exits with 0 if no update available, 1 if an update is available
- [ ] `dmpm install` - Installs all dependencies listed in the package manager
- [x] `dmpm help` - Show a help menu

Core:
- [ ] Update checker
- [ ] Handle linking of all packages and other files regarding them (including statics)
- [ ] Sane API error handling
- [x] Local store is `dmpm.json`

Other:
- [ ] Repo readme
- [ ] Repo CI
